def start(): 
    print("here the options of calclations that this program can do: \nmultiply \nsquare \nsubtracion \naddition \nsubtraction variable \nmultiplication variable \nline points \n division variable \naddition variable \npyramid volume \nsquare volume \nfinding distance with mph and time \nfinding mph with distance and time \nfinding volume of a sphere \nfinding time with distance and mph")
    input3 = input("what calculation would you like to do: ")
    if input3 == "multiply": multiply()
    if input3 == "square": square()
    if input3 == "subtraction": subtraction()
    if input3 == "addition": addition()
    if input3 == "subtraction variable": variable1()
    if input3 == "multiplication variable": variable2()
    if input3 == "line points": line_points()
    if input3 == "division variable": variable3()
    if input3 == "addition variable": variable4()
    if input3 == "pyramid volume": pyramid_volume()
    if input3 == "square volume": square_volume()
    if input3 == "finding distance with mph and time": finding_distance_with_mph_and_time()
    if input3 == "finding mph with distance and time": finding_mph_with_distance_and_time()
    if input3 == "finding time with distance and mph": finding_time_with_distance_and_mph()
    if input3 == "finding volume of a sphere": finding_volume_of_a_sphere()
    else: print("sorry, could not find that. \n please try again"), start()
def square():
    input1 = input("enter number one: ")
    input2 = input("enter number two: ")
    var1 = int(input1)
    var2 = int(input2)
    result = pow(var1, var2)
    print(result)
    input3 = input("do you want to calculate something else? ")
    if input3 =="yes": input4 = input('would you like to use this topic or try somthing else (if somthing else write "somthing else". if you would like to do this again, write "again"):')
    else: print("sorry, could not get that try again"), start()
    if input3 =="something else": print("okay"), start()
    if input3 =="again": print("okay"), square() 
def multiply():
    input4 = input("enter number one: ")
    input5 = input("enter number two: ")
    var5 = int(input4)
    var4 = int(input5)
    result = (var5*var4)
    print(result)
    input3 = input("do you want to calculate something else? ")
    if input3 =="yes": input4 = input('would you like to use this topic or try somthing else (if somthing else write "somthing else". if you would like to do this again, write "again"):')
    else: print("sorry, could not get that try again"), start()
    if input3 =="something else": print("okay"), start()
    if input3 =="again": print("okay"), multiply()
def addition():
    input1 = input("enter number one: ")
    input2 = input("enter number two: ")
    var1 = int(input1)
    var2 = int(input2)
    result = (var1+var2)
    print(result)
    input3 = input("do you want to calculate something else? ")
    if input3 =="yes": input4 = input('would you like to use this topic or try somthing else (if somthing else write "somthing else". if you would like to do this again, write "again"):')
    else: print("sorry, could not get that try again"), start()
    if input3 =="something else": print("okay"), start()
    if input3 =="again": print("okay"), addition()
def variable1():
    input1 = input("enter the number that you will add to the mistery number: ")
    input2 = input("enter the answer: ")
    var1 = int(input1)
    var2 = int(input2)
    result = var2 - var1
    print(result)
    input3 = input("do you want to calculate something else? ")
    if input3 =="yes": input4 = input('would you like to use this topic or try somthing else (if somthing else write "somthing else". if you would like to do this again, write "again"):')
    else: print("sorry, could not get that try again"), start()
    if input3 =="something else": print("okay"), start()
    if input3 =="again": print("okay"), variable1()
def variable2():
    input1 = input("enter the number like to multiply the mistery number by: ")
    input2 = input("enter the result: ")
    var1 = int(input1)
    var2 = int(input2)
    result = var2/var1
    print(result)
    input3 = input("do you want to calculate something else? ")
    if input3 =="yes": input4 = input('would you like to use this topic or try somthing else (if somthing else write "somthing else". if you would like to do this again, write "again"):')
    else: print("sorry, could not get that try again"), start()
    if input3 =="something else": print("okay"), start()
    if input3 =="again": print("okay"), variable2()
def line_points():
    input1 = input("enter the difference: ")
    input2 = input("enter the spaces inbetween: ")
    var1 = int(input1)
    var2 = int(input2)
    result = var1/var2
    print(f"the difference between each tick mark is {result}")
    input3 = input("do you want to calculate something else? ")
    if input3 =="yes": input4 = input('would you like to use this topic or try somthing else (if somthing else write "somthing else". if you would like to do this again, write "again"):')
    else: print("sorry, could not get that try again"), start()
    if input3 =="something else": print("okay"), start()
    if input3 =="again": print("okay"), line_points()
def variable3():
    input1 = input("enter the number you want to divide the mistery number by: ")
    input2 = input("enter result: ")
    var1 = int(input1)
    var2 = int(input2)
    result = var2 * var1
    print(result)
    input3 = input("do you want to calculate something else? ")
    if input3 =="yes": input4 = input('would you like to use this topic or try somthing else (if somthing else write "somthing else". if you would like to do this again, write "again"):')
    else: print("sorry, could not get that try again"), start()
    if input3 =="something else": print("okay"), start()
    if input3 =="again": print("okay"), variable2()
def subtraction():
    input1 = input("enter the first number: ")
    input2 = input("enter the second number: ")
    var1 = int(input1)
    var2 = int(input2)
    result = var1 - var2
    print(result)
    input3 = input("do you want to calculate something else? ")
    if input3 =="yes": input4 = input('would you like to use this topic or try somthing else (if somthing else write "somthing else". if you would like to do this again, write "again"):')
    else: print("sorry, could not get that try again"), start()
    if input3 =="something else": print("okay"), start()
    if input3 =="again": print("okay"), subtraction()
def variable4():
    input1 = input("enter the number you would like to add to the mistery number: ")
    input2 = input("enter the result: ")
    var1 = int(input1)
    var2 = int(input2)
    result = var2 + var1
    print(result)
    input3 = input("do you want to calculate something else? ")
    if input3 =="yes": input4 = input('would you like to use this topic or try somthing else (if somthing else write "somthing else". if you would like to do this again, write "again"):')
    else: print("sorry, could not get that try again"), start()
    if input3 =="something else": print("okay"), start()
    if input3 =="again": print("okay"), variable4()
def pyramid_volume():
    input1 = input("enter the lenght: ")
    input2 = input("enter the width: ")
    input3 = input("enter the hight")
    var1 = int(input1)
    var2 = int(input2)
    var3 = int(input3)
    result = var1 * var2 * var3 / 3
    print(result)
    input3 = input("do you want to calculate something else? ")
    if input3 =="yes": input4 = input('would you like to use this topic or try somthing else (if somthing else write "somthing else". if you would like to do this again, write "again"):')
    else: print("sorry, could not get that try again"), start()
    if input3 =="something else": print("okay"), start()
    if input3 =="again": print("okay"), pyramid_volume()
def square_volume():
    input1 = input("enter the perimeter of one side: ")
    var1 = int(input1)
    result = var1 * var1 * var1
    print(result)
    input3 = input("do you want to calculate something else? ")
    if input3 =="yes": input4 = input('would you like to use this topic or try somthing else (if somthing else write "somthing else". if you would like to do this again, write "again"):')
    else: print("sorry, could not get that try again"), start()
    if input3 =="something else": print("okay"), start()
    if input3 =="again": print("okay"), square_volume()
def finding_distance_with_mph_and_time():
    input1 = input("enter mph: ")
    input2 = input("enter time: ")
    var1 = int(input1)
    var2 = int(input2)
    result = var1 * var2
    print(f"the distance that would have been traveled is {result} miles")
    input3 = input("do you want to calculate something else? ")
    if input3 =="yes": input4 = input('would you like to use this topic or try somthing else (if somthing else write "somthing else". if you would like to do this again, write "again"):')
    else: print("sorry, could not get that try again"), start()
    if input4 =="something else": print("okay"), start()
    if input4 =="again": print("okay"), finding_distance_with_mph_and_time()
def finding_mph_with_distance_and_time():
    input1 = input("enter distance (miles): ")
    input2 = input("enter time: ")
    var1 = int(input1)
    var2 = int(input2)
    result = var2 / var1
    print(f"the speed is {result} mph")
    input3 = input("do you want to calculate something else? ")
    if input3 =="yes": input4 = input('would you like to use this topic or try somthing else (if somthing else write "somthing else". if you would like to do this again, write "again"):')
    else: print("sorry, could not get that try again"), start()
    if input3 =="something else": print("okay"), start()
    if input3 =="again": print("okay"), finding_mph_with_distance_and_time()
def finding_time_with_distance_and_mph():
    input1 = input("enter mph: ")
    input2 = input("enter distance (miles): ")
    var1 = int(input1)
    var2 = int(input2)
    try:
        result = var2 / var1
    except ZeroDivisionError:
        print("please enter digits larger than zero. \ntry again"), finding_time_with_distance_and_mph()
    except ValueError:
        print("please enter a number"), finding_time_with_distance_and_mph()
    print(result)
    input3 = input("do you want to calculate something else? ")
    if input3 =="yes": 
        input4 = input('would you like to use this topic or try somthing else (if somthing else write "somthing else". if you would like to do this again, write "again"):'),
        if input4 =="something else": print("okay"), start()
        elif input4 =="again": finding_mph_with_distance_and_time()
        else: print("sorry, could not get that try again"), start()
def finding_volume_of_a_sphere():
    input1 = input("enter radius: ")
    var1 = int(input1)
    result = "under construction"
    print(result)
    input3 = input("do you want to calculate something else? ")
    if input3 =="yes": input4 = input('would you like to use this topic or try somthing else (if somthing else write "somthing else". if you would like to do this again, write "again"):')
    if input3 =="something else": print("okay"), start()
    if input3 =="again": print("okay"), finding_mph_with_distance_and_time()
    else: print("sorry, could not get that try again"), start()


start()